# Generated by Django 3.0.6 on 2020-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='learnpoints',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ponits_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('learntime', models.DecimalField(decimal_places=1, max_digits=6)),
                ('points', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
